// AUTHENTICATION
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

// STUDENTS
export const COMPLETE_S_PROFILE_SUCCESS = 'COMPLETE_S_PROFILE_SUCCESS'
export const COMPLETE_S_PROFILE_FAIL = 'COMPLETE_S_PROFILE_FAIL'
export const GET_S_PROFILES_SUCCESS = 'GET_S_PROFILES_SUCCESS'
export const GET_S_PROFILES_FAIL = 'GET_S_PROFILES_FAIL'
export const GET_SINGLE_S_PROFILE_SUCCESS = 'GET_SINGLE_S_PROFILE_SUCCESS'
export const GET_SINGLE_S_PROFILE_FAIL = 'GET_SINGLE_S_PROFILE_FAIL'

// COMPANIES
export const COMPLETE_C_PROFILE_SUCCESS = 'COMPLETE_C_PROFILE_SUCCESS'
export const COMPLETE_C_PROFILE_FAIL = 'COMPLETE_C_PROFILE_FAIL'
export const GET_C_PROFILES_SUCCESS = 'GET_C_PROFILES_SUCCESS'
export const GET_C_PROFILES_FAIL = 'GET_C_PROFILES_FAIL'
export const GET_SINGLE_C_PROFILE_SUCCESS = 'GET_SINGLE_C_PROFILE_SUCCESS'
export const GET_SINGLE_C_PROFILE_FAIL = 'GET_SINGLE_C_PROFILE_FAIL'

// JOBS
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS'
export const ADD_JOB_FAIL = 'ADD_JOB_FAIL'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL'
export const GET_SINGLE_JOB_SUCCESS = 'GET_SINGLE_JOB_SUCCESS'
export const GET_SINGLE_JOB_FAIL = 'GET_SINGLE_JOB_FAIL'
